USE shopdb;


SELECT * FROM memberTBL;

SELECT * FROM shopdb.memberTBL;

SELECT memberID, memberAddress FROM shopdb.memberTBL;

SELECT * FROM memberTBL WHERE memberName = '토마스';

CREATE TABLE `my testTBL`(ID INT);

DROP TABLE `my testTBL`;

CREATE TABLE INDEXTBL (FIRST_NAME VARCHAR(14), LAST_NAME VARCHAR(16), HIRE_DATE DATE);

INSERT INTO INDEXTBL
	SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
	FROM employees.employees
LIMIT 500;

SELECT * FROM INDEXTBL;

#Full table Scan
SELECT * FROM INDEXTBL WHERE `FIRST_NAME` = 'MARY';

#Index Create
CREATE INDEX IDX_INDEXTBL_FIRSTNAME ON INDEXTBL(FIRST_NAME);

#rescan -> Index Info
SELECT * FROM INDEXTBL WHERE FIRST_NAME = 'MARY';


CREATE VIEW UB_MEMBERTBL
AS SELECT MEMBERNAME, MEMBERADDRESS FROM memberTBL;

SELECT * FROM shopdb.UB_MEMBERTBL;

SELECT * FROM shopdb.UB_MEMBERTBL WHERE MEMBERNAME = '토마스';
SELECT * FROM productTBL where PRODUCTNAME = '냉장고';

DELIMITER //
CREATE PROCEDURE MYPROC()
BEGIN
SELECT * FROM memberTBL WHERE MEMBERNAME = '토마스';
SELECT * FROM productTBL where PRODUCTNAME = '냉장고';
END //
DELIMITER ;

CALL MYPROC();

DROP PROCEDURE MYPROC;

INSERT INTO memberTBL VALUES ('SOCCER', '흥민', '서울시 서대문구 북가좌동');
UPDATE memberTBL SET memberAddress = '서울 강남구 역삼동' WHERE memberName = '흥민';
DELETE FROM memberTBL WHERE memberName = '흥민';

CREATE TABLE DELETEDMEMBERTBL
(
MEMBERID CHAR(8),
MEMBERNAME CHAR(5),
MEMBERADDRESS CHAR(20),
DELETEDDATE DATE
);

DROP TABLE DELETEDMEMBERTBL;

DELIMITER //
CREATE TRIGGER TRG_DELETEDMEMBERTBL
AFTER DELETE
ON memberTBL
FOR EACH ROW
BEGIN 
INSERT INTO shopdb.DELETEDMEMBERTBL
VALUES (OLD.MEMBERID, OLD.MEMBERNAME, OLD.MEMBERADDRESS, curdate());
END //
DELIMITER ;

DROP TRIGGER TRG_DELETEDMEMBERTBL;

SELECT * FROM memberTBL;

INSERT INTO MEMBERTBL VALUES ('SOCCER', '흥민', '서울시 서대문구 북가좌동');
UPDATE memberTBL SET memberAddress = '서울 강남구 역삼동' WHERE memberName = '흥민';
DELETE FROM memberTBL WHERE memberID = 'SOCCER';

SELECT * FROM memberTBL;

SELECT * FROM DELETEDMEMBERTBL;

CREATE TABLE `memberTBL` (
  `memberID` char(8) NOT NULL COMMENT '아이디',
  `memberName` char(5) NOT NULL COMMENT '회원 이름',
  `memberAddress` char(20) DEFAULT NULL COMMENT '주소',
  PRIMARY KEY (`memberID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

#View Create...
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `shopdb`.`UB_MEMBERTBL` AS select `shopdb`.`memberTBL`.`memberName` AS `MEMBERNAME`,`shopdb`.`memberTBL`.`memberAddress` AS `MEMBERADDRESS` from `shopdb`.`memberTBL`;


USE employees;
SELECT * FROM employees;

use shopDB;
select * from membertbl;

USE employees;
SELECT * FROM titles;

USE ShopDB;
CREATE TABLE test (id INT);

USE ShopDB;
CREATE TABLE test (id INT);
INSERT INTO test VALUES(1);

USE employees;
SELECT * FROM employees;

CREATE DATABASE sampleDB;
DROP DATABASE sampleDB;

USE ShopDB;
SELECT * FROM memberTBL;
DELETE FROM memberTBL WHERE memberID = 'Gorden';
DROP TABLE memberTBL;

